-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTSlNEo+ehNewn8Ar
skUGsw+U9C2ngWce+WpukqeYqfmgCgYIKoZIzj0DAQehRANCAAR/Sz0yqf7jN/cB
yKYOJxa4GXkfrMkmYqOFNieYaqPGfpfjIbpnlNpUNqSw4w+k8qNth0gpWp9md3Pd
6YKIUzPN
-----END PRIVATE KEY-----